language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dcokerfile.dev -t sathyabodh/docker-react .

script:
  - docker run -e CI=true sathyabodh/docker-react npm run test
